In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3,4,5],[1,2,3,4,5]],dtype=int)
print(a)

[[1 2 3 4 5]
 [1 2 3 4 5]]


In [4]:
print(type(a))
print(len(a))
print(a.ndim)
print(a.shape)

<class 'numpy.ndarray'>
2
2
(2, 5)


In [5]:
a1 = a.reshape(2,5)
print(a1)
print(a1.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [6]:
a2 = a.reshape(5,-1)
print(a2)

[[1 2]
 [3 4]
 [5 1]
 [2 3]
 [4 5]]


In [7]:
print(a2.ndim)

2


In [8]:
%%time
l1 = [1,2,3,4,5]
l2 = [2,3,4,5,6]
l3 = [9,7,6,8,9]

mul_l = np.array([l1,l2,l3],dtype=int)
#print(mul_l.shape)
mul_l = mul_l.reshape(1,15)
print(mul_l.shape)
print(mul_l)

(1, 15)
[[1 2 3 4 5 2 3 4 5 6 9 7 6 8 9]]
Wall time: 499 µs


In [9]:
mul_l.shape = (3,5)
print(mul_l)

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [10]:
r  = range(24)
r

range(0, 24)

In [11]:
a1 = np.arange(24)
print(a1)
print(a1.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1


In [12]:
b = a1.reshape(6,2,2)
print(b)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]

 [[20 21]
  [22 23]]]


In [13]:
x = np.array([1,2,3,4,5], dtype = np.int8)
print(x.itemsize)

1


In [14]:
x = np.array([1,2,3,4,5], dtype = np.int32)
print(x.itemsize)
x = np.array([1,2,3,4,5], dtype = np.int64)
print(x.itemsize)

4
8


In [15]:
x = np.array([[1,2],[3,4]],dtype = np.float64)
y = np.array([[5,6],[7,8]],dtype = np.float64)
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [16]:
print(x+y)

[[ 6.  8.]
 [10. 12.]]


In [17]:
print(np.add(x,y))

[[ 6.  8.]
 [10. 12.]]


In [18]:
print(x-y)

[[-4. -4.]
 [-4. -4.]]


In [19]:
print(np.subtract(x,y))

[[-4. -4.]
 [-4. -4.]]


In [20]:
print(x)
print(y)
print(x*y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[ 5. 12.]
 [21. 32.]]


In [21]:
print(np.multiply(x,y))

[[ 5. 12.]
 [21. 32.]]


In [22]:
print(x)
print(y)
print(np.dot(x,y)) #matrix multiplication

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[19. 22.]
 [43. 50.]]


In [23]:
print(x)
print(y)
print(np.divide(x,y))

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [24]:
print(x/y)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [25]:
print(np.sum(x))

10.0


In [26]:
print(np.sum(x, axis=0))

[4. 6.]


In [27]:
print(np.sum(x, axis=1))

[3. 7.]


In [32]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [35]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [38]:
np.random.rand(5,5)

array([[0.70139299, 0.97053816, 0.76878328, 0.78243071, 0.6254806 ],
       [0.51445826, 0.61712515, 0.57078502, 0.0646338 , 0.59615391],
       [0.68245078, 0.02527595, 0.35008573, 0.70026666, 0.67735774],
       [0.94818667, 0.81106094, 0.39393055, 0.44454676, 0.62865448],
       [0.5143576 , 0.03422451, 0.93032803, 0.67588856, 0.40927504]])

In [40]:
np.random.randn(5)

array([ 0.79874071,  0.32536748,  2.21222659, -0.50185226,  0.01328972])

In [44]:
np.random.randint(1,100,10)

array([10, 17, 95, 19, 10, 64, 48, 34, 73, 12])

In [45]:
arr = np.arange(25)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [47]:
ranarr = np.random.randint(0,50,10)

In [48]:
ranarr

array([ 5, 38, 25,  6, 28,  9, 33, 27, 49,  0])

In [51]:
ranarr.max()

49

In [54]:
ranarr.min()

0

In [53]:
ranarr.argmin()

9

In [55]:
ranarr.argmax()

8

In [61]:
arr.shape

(25,)

In [60]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
arr.dtype

dtype('int32')

In [63]:
from numpy.random import randint

In [64]:
randint(2,10)

9

In [88]:
arr = np.arange(0,11)

In [89]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
slice_of_arr = arr[0:5]

In [91]:
slice_of_arr[:] = 99

In [92]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [93]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [94]:
arr_copy = arr[0:5].copy()

In [95]:
arr_copy

array([99, 99, 99, 99, 99])

In [96]:
arr_copy[:] = 100

In [97]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [98]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [99]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [106]:
arr_2d[2,1] 
#or
arr_2d[2][1]


40

In [117]:
arr_2d[:2,1:] 

array([[10, 15],
       [25, 30]])

In [118]:
arr = np.arange(1,11)

In [119]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [122]:
bool_arr = arr > 5

In [123]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [124]:
arr[arr<3]

array([1, 2])

In [125]:
arr_2d = np.arange(50).reshape(5,10)

In [132]:
arr_2d[1:3]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [134]:
arr = np.arange(0,11)

In [135]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [136]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [137]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [138]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [139]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [140]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [141]:
1/0

ZeroDivisionError: division by zero

In [142]:
arr / arr

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [143]:
arr / 0

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan, inf, inf, inf, inf, inf, inf, inf, inf, inf, inf])

In [144]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [145]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [146]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [147]:
np.max(arr)

10

In [148]:
arr.max()

10

In [149]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [150]:
np.log(arr)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])